version: '3.9'
services:
  frontend:
    build: ./web-chatbot-frontend
    container_name: app_frontend
    ports:
      - 3000:3000
    platform: linux/x86_64
  backend:
    build: ./web-chatbot-backend
    container_name: app_backend
    ports:
      - 3002:3002
    platform: linux/x86_64
    restart: 'always'
    depends_on:
      db:
        condition: service_healthy
    environment:
      - DB_USERNAME=root
      - DB_PASSWORD=root@123
      - DB_HOST=db
      - DB_DATABASE=webchatbot
      - DB_PORT=3306
      - JWT_SECRET="Wfw!aX60yMVp9jH853!3ERMX$M6pCiIJ"
  db:
    image: mysql:latest
    platform: linux/x86_64
    container_name: db
    ports:
      - 3003:3306
    environment:
      - MYSQL_DATABASE=webchatbot 
      - MYSQL_ROOT_PASSWORD=root@123
    restart: 'always'
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      timeout: 10s
      retries: 5
    cap_add:
      - SYS_NICE